name = "diocesecaruaru"
compatibility_date = "2025-10-02"

pages_build_output_dir = "dist"

[build]
command = "npm ci && npm run build"

[build.environment_variables]
NODE_VERSION = "20.18.0"
NPM_FLAGS = "--legacy-peer-deps"
